### ISSUE TITLE
Showing blank page

### ISSUE THREAD

**Issue by amitgaur208** [dereklin/angular-cli-owl-carousel#1]
Not working at all

**Comment by dereklin** [comment]
@amitgaur208 Please take a look at this: https://github.com/angular/angular-cli/issues/4838

I haven't had time to give the work around try.  Please do let me know if you get it working.  A pull request would be nice.

If you want to use owl carousel in angular 2+, you can check out my other project: https://github.com/dereklin/ng-ws-ngrx-hmr-heroku.  It's not angular cli.  It's using https://github.com/AngularClass/angular2-webpack-starter

**Comment by dereklin** [comment]
should be fixed now.
